config_version: '1.6'
container_opts:
  image: ${IMAGE}
languages:
  go:
    generation:
      default:
        templates:
          source:
            type: openapi-jar
            # Path inside the container openapitools/openapi-generator-cli:v5.2.1
            jar_path: /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar
            templates_dir: go
          patches:
            - template-patches/go/client_patch_default_headers.patch
            - template-patches/go/client_remove_default.patch
            - template-patches/go/configuration_context.patch
            - template-patches/go/identity_providers.patch
            - template-patches/go/utils_big_int.patch
            - template-patches/go/download_file.patch
            - template-patches/go/redact_http_auth.patch
        commands:
          - commandline:
            - docker-entrypoint.sh
            - generate
            - --http-user-agent
            - '{{user_agent_client_name}}/{{library_version}}/{{language_name}}'
            - -g
            - '{{language_name}}'
            - -c
            - '{{language_config}}'
            - -i
            - '{{full_spec_path}}'
            - -o
            - '{{version_output_dir}}'
            # - --additional-properties
            # - apigentoolsStamp='{{stamp}}'
            - -t
            - "{{templates_dir}}"
            description: Generate code using openapi-generator
          - commandline:
            - rm
            - -rf
            - docs
            description: Remove unwanted docs folder
          - commandline:
            - rm
            - -rf
            - api
            description: Remove openapi yaml
          - commandline:
            - go
            - mod
            - download
            - golang.org/x/oauth2
            description: go dep
            container_opts:
              system: true
          - commandline:
            - gofmt
            - -w
            - .
            description: go fmt
            container_opts:
              system: true



    github_repo_name: sdp-api-client-go
    github_org_name: appgate
    library_version: "0.0.1"
    spec_versions: ["v16", "v17", "v18", "v19", "v20"]
    version_path_template: "openapi_{{spec_version}}"
spec_sections:
  v18:
  - api_specs.yml
  v19:
  - api_specs.yml
  v20:
  - api_specs.yml

validation_commands:
  - commandline:
    - docker-entrypoint.sh
    - validate
    - -i
    - '{{cwd}}/spec/{{spec_version}}/api_specs.yml'
    description: "Validate the full spec using openapi-generator"

spec_versions:
- v16
- v17
- v18
- v19
- v20
