config_version: '1.6'
container_opts:
  image: openapitools/openapi-generator-cli:v5.2.1
languages:
  go:
    downstream_templates:
      # the templates for identity_providers is because of how the openapi-generator treat discriminator objects.
      # The default baviour within openapi-generator is to create 1 api service for all, but that does not really work well
      # in practice because we need a way in the code to have seperate models for each type of identity providers,
      # that is why we create a copy for each type in the discriminator object based on the default api_identity_providers.go
      # the only diffrence is the service name and the models used in the arguments, the patch template-patches/go/identity_providers.patch
      # will append the extra services to the client.
      downstream_templates/go/api_connector_identity_providers.go: openapi/api_connector_identity_providers.go
      downstream_templates/go/api_local_database_identity_providers.go: openapi/api_local_database_identity_providers.go
      downstream_templates/go/api_ldap_certificate_identity_providers.go: openapi/api_ldap_certificate_identity_providers.go
      downstream_templates/go/api_saml_identity_providers.go: openapi/api_saml_identity_providers.go
      downstream_templates/go/api_radius_identity_providers.go: openapi/api_radius_identity_providers.go
      downstream_templates/go/api_ldap_identity_providers.go: openapi/api_ldap_identity_providers.go
      downstream_templates/go/model_identity_provider_list.go: openapi/model_identity_provider_list.go
    generation:
      default:
        templates:
          source:
            type: openapi-jar
            # Path inside the container openapitools/openapi-generator-cli:v5.2.1
            jar_path: /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar
            templates_dir: go
          patches:
            - template-patches/go/client_patch_default_headers.patch
            - template-patches/go/identity_providers.patch
            - template-patches/go/utils_big_int.patch
        commands:
          - commandline:
            - docker-entrypoint.sh
            - generate
            - --http-user-agent
            - '{{user_agent_client_name}}/{{library_version}}/{{language_name}}'
            - -g
            - '{{language_name}}'
            - -c
            - '{{language_config}}'
            - -i
            - '{{full_spec_path}}'
            - -o
            - '{{version_output_dir}}'
            # - --additional-properties
            # - apigentoolsStamp='{{stamp}}'
            - -t
            - "{{templates_dir}}"
            description: Generate code using openapi-generator
          - commandline:
            - rm
            - -rf
            - docs
            description: Remove unwanted docs folder
          - commandline:
            - rm
            - -rf
            - api
            description: Remove openapi yaml
          - commandline:
            - go
            - mod
            - download
            - golang.org/x/oauth2
            description: go dep
            container_opts:
              system: true
          - commandline:
            - go
            - fmt
            - ./...
            description: go fmt
            container_opts:
              system: true

    github_repo_name: sdp-api-client-go
    github_org_name: appgate
    library_version: "0.0.1"
    spec_versions: ["v16"]
    version_path_template: openapi
spec_sections:
  v16:
  - api_specs.yml

validation_commands:
  - commandline:
    - docker-entrypoint.sh
    - validate
    - -i
    - '{{cwd}}/spec/{{spec_version}}/api_specs.yml'
    description: "Validate the full spec using openapi-generator"

spec_versions:
- v16
