name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.2'


    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Fmt check
      run:  if [[ $(gofmt -l -s ./api | wc -l) -gt 0 ]]; then echo "you need to run go fmt ./api/..." && exit 1; fi

    - name: Unit tests
      run: go test -v -count 1 ./api/...

  lint:
    name: "Static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: "1.20.x"
      - run: "GO111MODULE=on go install honnef.co/go/tools/cmd/staticcheck@2023.1.2"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: ~/.cache/staticcheck
          key: staticcheck-${{ github.sha }}
          restore-keys: |
            staticcheck-
      - run: "go vet ./api/..."
      - run: "$(go env GOPATH)/bin/staticcheck ./api/..."
